In [3]:
# importing module
import numpy as np

In [4]:
# generating random float
np.random.rand()

# genrating array with randome floats
np.random.rand(2,2)

# generating random integer in a range
np.random.randint(1,10)

# genrate array with random integer
np.random.randint(1,20,(5,5))

array([[ 6, 19,  7, 14,  3],
       [ 1,  6, 14,  2,  3],
       [17, 13, 17, 18,  4],
       [ 8, 16,  3, 12,  3],
       [12,  3, 17,  3,  2]], dtype=int32)

In [5]:
# Assignment:1
array1 = np.random.randint(low=1,high=21,size=(5,5))
print(array1)

array1[2] = 1

print("Modified array: \n",array1)

[[ 8  8 17  3  7]
 [11 13 17  2 14]
 [ 5 14  4  3 15]
 [ 9 15  2 12  9]
 [19  8 10  1  2]]
Modified array: 
 [[ 8  8 17  3  7]
 [11 13 17  2 14]
 [ 1  1  1  1  1]
 [ 9 15  2 12  9]
 [19  8 10  1  2]]


In [6]:
# Assignment 1
array1_b = np.random.randint(1,17,(4,4))
print('original array: \n', array1_b)

original array: 
 [[ 4  9  9 14]
 [ 6  5  2 13]
 [ 1 14  5 10]
 [ 3  2 12 10]]


In [7]:
for row_num,row in enumerate(array1_b):
    # print('current row:', row_num)

    for col_num, col in enumerate(row):
        # print('current col in row:', col_num)

        if col_num == row_num :
            # print("col val before:",col)
            array1_b[row_num][col_num] = 0
            # print("col val after:",col)
            break
print(array1_b)

[[ 0  9  9 14]
 [ 6  0  2 13]
 [ 1 14  0 10]
 [ 3  2 12  0]]


In [8]:
np.fill_diagonal(array1_b,1)
array1_b

array([[ 1,  9,  9, 14],
       [ 6,  1,  2, 13],
       [ 1, 14,  1, 10],
       [ 3,  2, 12,  1]], dtype=int32)

In [9]:
# Assignment 2
array2a = np.random.randint(1,36,size=(6,6))
print("original array:\n",array2a)

original array:
 [[27  9 29 15  6  2]
 [28 28 34 10 31 24]
 [ 5 19 13 26 10  4]
 [35  5 12 20  7 34]
 [35  1  2 35 35 35]
 [ 8 28 22  2 24  2]]


In [10]:
subarray1 = array2a[2:5]
subarray1

array([[ 5, 19, 13, 26, 10,  4],
       [35,  5, 12, 20,  7, 34],
       [35,  1,  2, 35, 35, 35]], dtype=int32)

In [11]:
print(array2a[:,1:4])

[[ 9 29 15]
 [28 34 10]
 [19 13 26]
 [ 5 12 20]
 [ 1  2 35]
 [28 22  2]]


In [12]:
# assignment 2b
array = np.random.randint(1,25,(5,5))
print('Original Array: \n',array)



Original Array: 
 [[21  8 23  4 12]
 [22 13  7 18 12]
 [23  8 17  8  4]
 [ 8 14 20 18  5]
 [21  2  2  5  3]]


In [13]:
border_elements = np.concatenate((array[0,:], array[-1,:], array[1:-1,0],array[1:-1,-1]))

print(border_elements)

[21  8 23  4 12 21  2  2  5  3 22 23  8 12  4  5]


In [14]:
# Assignment 3
array3_1 = np.random.randint(1,12,size=(3,4))
array3_2 = np.random.randint(13,25,size=(3,4))
print(array3_1)
print("\n")
print(array3_2)

[[ 5  9  4  2]
 [10  7  5  3]
 [ 7  3 11  9]]


[[17 19 20 23]
 [21 17 13 13]
 [22 22 17 14]]


In [15]:
# array element wise operation
print("addition: \n", array3_1+array3_2)
print("substraction: \n", array3_1-array3_2)
print("multiplication: \n", array3_1*array3_2)
print("division: \n", array3_1/array3_2)

addition: 
 [[22 28 24 25]
 [31 24 18 16]
 [29 25 28 23]]
substraction: 
 [[-12 -10 -16 -21]
 [-11 -10  -8 -10]
 [-15 -19  -6  -5]]
multiplication: 
 [[ 85 171  80  46]
 [210 119  65  39]
 [154  66 187 126]]
division: 
 [[0.29411765 0.47368421 0.2        0.08695652]
 [0.47619048 0.41176471 0.38461538 0.23076923]
 [0.31818182 0.13636364 0.64705882 0.64285714]]


In [16]:
# 4
array = np.random.randint(1,17,(4,4))
array

array([[ 4,  2, 12,  3],
       [ 1,  7, 12, 10],
       [15,  6, 14,  6],
       [15,  3, 12,  4]], dtype=int32)

In [17]:
lst = []
print(lst)

[]


In [18]:
# row wise addition
for row_num, row in enumerate(array):
    sum = 0
    for col_num, col in enumerate(row):
        sum = sum + col
    lst.append(sum)

print(lst)


[np.int32(21), np.int32(30), np.int32(41), np.int32(34)]


In [19]:
array_shape = array.shape
col_size = array_shape[1]
col_sum_lst = []

# col wise addition
for i in range(0,col_size):
    data = array[:,i]
    print(data)
    sum = 0
    for j in data:
        sum = sum + j
    col_sum_lst.append(sum)

print(col_sum_lst)


[ 4  1 15 15]
[2 7 6 3]
[12 12 14 12]
[ 3 10  6  4]
[np.int32(35), np.int32(18), np.int32(50), np.int32(23)]


In [20]:
row = np.sum(array,axis=0)
print(row)
col = np.sum(array,axis=1)
print(col)

[35 18 50 23]
[21 30 41 34]


In [22]:
# 4
array = np.random.randint(1,26,(5,5))
array

array([[14, 22, 24,  7, 25],
       [15, 12,  7, 17,  2],
       [20, 24, 14,  4,  8],
       [22, 16, 14, 14, 18],
       [19, 23, 11, 15,  8]], dtype=int32)

In [23]:
mean = np.mean(array)
median = np.median(array)
standard_deviation = np.std(array)
varience = np.var(array)

print(mean, median, standard_deviation, varience)

15.0 15.0 6.4 40.96


In [24]:
array = np.random.randint(1,10,(3,3))
array

array([[3, 9, 1],
       [2, 5, 2],
       [8, 5, 8]], dtype=int32)

In [25]:
# normalizing array
mean = array.mean()
std = array.std()

normalized_Array = (array-mean)/std
print(normalized_Array)

[[-0.63048832  1.49740977 -1.33978769]
 [-0.98513801  0.07881104 -0.98513801]
 [ 1.14276009  0.07881104  1.14276009]]


In [27]:
array = np.random.randint(1,10,(3,3))
print(array)
array1 = np.random.randint(1,10,(3))
print(array1)

[[4 9 2]
 [8 6 3]
 [6 7 2]]
[8 3 2]


In [28]:
print("addition: \n",array+array1)

addition: 
 [[12 12  4]
 [16  9  5]
 [14 10  4]]


In [30]:
array = np.random.randint(1,10,(4,4))
print(array)

array1 = np.random.randint(1,10,(4))
print(array1)

result = array-array1[:, np.newaxis]
print("result: \n", result)


[[6 6 2 4]
 [7 8 6 9]
 [2 9 1 2]
 [7 5 9 7]]
[5 8 3 7]
result: 
 [[ 1  1 -3 -1]
 [-1  0 -2  1]
 [-1  6 -2 -1]
 [ 0 -2  2  0]]


In [36]:
# assignment 6
array = np.random.randint(1,10,(3,3))
print(array)

determinant = np.linalg.det(array)
print('determinant: \n', determinant)

inverse = np.linalg.inv(array)
print('Inverse: \n',inverse) 

eigenvalues = np.linalg.eig(array)
print('eigen values: \n',eigenvalues)

[[3 1 9]
 [7 4 5]
 [5 2 4]]
determinant: 
 -38.99999999999998
Inverse: 
 [[-0.15384615 -0.35897436  0.79487179]
 [ 0.07692308  0.84615385 -1.23076923]
 [ 0.15384615  0.02564103 -0.12820513]]
eigen values: 
 EigResult(eigenvalues=array([12.50944765, -2.67494561,  1.16549796]), eigenvectors=array([[-0.52292727, -0.76479964,  0.35589448],
       [-0.7085634 ,  0.48082853, -0.93400401],
       [-0.47379846,  0.42881865,  0.03123498]]))


In [39]:
# assignment 7
array = np.random.randint(1,10,(3,3))
print(array)

print(array.reshape(1,9))
print(array.reshape(9,1))

[[4 8 2]
 [5 3 3]
 [4 6 6]]
[[4 8 2 5 3 3 4 6 6]]
[[4]
 [8]
 [2]
 [5]
 [3]
 [3]
 [4]
 [6]
 [6]]


In [40]:
# fancy indexing and boolean expressing
array = np.random.randint(1,30,(5,5))
print(array)

corners = array[[0,0,-1,-1], [0,-1,0,-1]]
print("Corner element in array: \n",corners)

[[ 4 15 11 12  9]
 [22  7 12 20  5]
 [ 5 29  6 20  6]
 [ 3 23  8 13  2]
 [26 19 13  7 14]]
Corner element in array: 
 [ 4  9 26 14]


In [43]:
array = np.random.randint(1,17,(4,4))
print("original array: \n",array)

original array: 
 [[12 13 12 10]
 [ 3  3  5 15]
 [ 6 10  3 15]
 [15  8  8 16]]


In [44]:
array[array>10] = 10

print("modified array: \n",array)

modified array: 
 [[10 10 10 10]
 [ 3  3  5 10]
 [ 6 10  3 10]
 [10  8  8 10]]


In [45]:
# Assignment 10
# masked array is used to handle invalid data
# a invalid data must not be accounted when working on dataset
# it skew the result
# masked elements are invalid 

import numpy.ma as ma


In [50]:
array = np.random.randint(1,17,(5))
print(array)

[10  8 15 11 15]


In [54]:
mx = ma.masked_greater(array, 10)
sum = mx.sum()
print(mx)
print(sum)

[10 8 -- -- --]
18


In [57]:
array = np.random.randint(1,10,(3,3))
print(array)


[[9 9 6]
 [3 8 8]
 [7 5 5]]


In [63]:
diagonal_elements = array.diagonal()
print(diagonal_elements)

masked_diagonal_array = ma.masked_values(array,diagonal_elements)
print(masked_diagonal_array)

[9 8 5]
[[-- 9 6]
 [3 -- 8]
 [7 5 --]]


In [68]:
val = masked_diagonal_array.mean()
print(val)

6.333333333333333


In [73]:
fixed_Array = masked_diagonal_array.filled(val)
print(fixed_Array)

[[6 9 6]
 [3 6 8]
 [7 5 6]]
