In [10]:
# importing Library
import numpy as np

In [11]:
# 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [12]:
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(5,)


In [ ]:
# 1D array
arr2 = np.array([1,2,3,4,5])
print(arr2)
print(arr2.shape)

# converting 1D array to 2D array
arr2 = arr2.reshape([1,5])
print(arr2)
print(arr2.shape)

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]]
(1, 5)


In [19]:
# initializing 2D array
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [ ]:
# gives multiple of 2's or skips 2's
arr_try = np.arange(0,10,2)
print(arr_try)

[0 2 4 6 8]


In [ ]:
# Initializes an array with all elements = 1
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
# identity matrix
#  with diagonal element as 1

identity_array = np.eye(3)
identity_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# important attributes of numpy
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("shape of array:",arr3.shape)
print("Dimension of array:",arr3.ndim)
print("Size of array:",arr3.size)
print("data type of elements:",arr3.dtype)
print("Size of item(in bytes):",arr3.itemsize)

shape of array: (2, 5)
Dimension of array: 2
Size of array: 10
data type of elements: int64
Size of item(in bytes): 8


In [31]:
# Vector Operation

# Addition
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print('Addition:', arr1+arr2)

# substraction
print('Substraction:',arr1-arr2)

# multiply
print('Multiply:',arr1*arr2)

# division
print('Divide:',arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiply: [ 10  40  90 160 250]
Divide: [0.1 0.1 0.1 0.1 0.1]


In [34]:
# universal Operation
arr1 = np.array([1,2,3,4,5])

# multiplication
print(arr1*5)

# square root
print(np.sqrt(arr1))

# Exponential
print(np.exp(arr1))

# sine
print(np.sin(arr1))

# log
print(np.log(arr1))


[ 5 10 15 20 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


## Slicing and Indexing

In [42]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]

])

print("Array: \n",arr)

Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [39]:
row0 = arr[0]
print(row0)
print(type(row0))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [40]:
row1 = arr[1]
row2 = arr[2]
print(row1, row2)

[ 6  7  8  9 10] [11 12 13 14 15]


In [41]:
# accessing elements inside row1
print(arr[1][0])
print(arr[1][1])
print(arr[1][2])
print(arr[1][3])
print(arr[1][4])

6
7
8
9
10


In [43]:
# slicing all row from 1 to end
print(arr[1:])

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [48]:
# selectively slicing inside the rows
print(arr[1:3,1:3])

[[ 7  8]
 [12 13]]


## Modifying array elements

In [50]:
# modifying selective elements
arr[0,0] = 100

# modifying range of elements
arr[1:3,2:4] = 0

print(arr)

[[100   2   3   4   5]
 [  6   7   0   0  10]
 [ 11  12   0   0  15]
 [ 16  17  18  19  20]]


## Normalization
- to have a mean of 0 and standard deviation of 1.

In [52]:
data = np.array([1,2,3,4,5,6])

mean = np.mean(data)
std_dev = np.std(data)

varience = np.var(data)
print(varience)

normalized_Data = (data-mean)/std_dev
print(normalized_Data)

2.9166666666666665
[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


## Logical Operation

In [57]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[data>5]

data[(data>3) & (data<8)]

array([4, 5, 6, 7])